#!/usr/bin/env python
from setuptools import setup

setup(
    name = "malstruct",
    version = open("VERSION").read(),
    packages = [
        "malstruct",
        "malstruct.lib",
        "malstruct.utils",
    ],
    license = "MIT",
    description = "A powerful declarative symmetric parser/builder for binary data",
    long_description = open("README.rst").read(),
    platforms = ["POSIX", "Windows"],
    url = "https://ciphertechsolutions.github.io/malstruct/",
    project_urls = {
        "Source": "https://github.com/ciphertechsolutions/malstruct",
        "Documentation": "https://ciphertechsolutions.github.io/malstruct/",
        "Issues": "https://github.com/ciphertechsolutions/malstruct/issues",
    },
    author="Cipher Tech Solutions, Inc",
    author_email="opensource@ciphertechsolutions.com",
    maintainer="Cipher Tech Solutions, Inc",
    maintainer_email="opensource@ciphertechsolutions.com",
    python_requires = ">=3.10",
    install_requires = [
        "numpy",
        "arrow",
        "ruamel.yaml",
        "cloudpickle",
        "lz4",
        "cryptography",
        "pyelftools",
        "jinja2",
        "pefile>=2019.4.18",
        "lief",
    ],
    package_data={
        "malstruct": ["utils/template.html"]
    },
    extras_require = {
        "all": [],
        "arm": [],
        "extras": [],
        "html": [],
        "pe": []
    },
    keywords = [
        "malstruct",
        "construct",
        "kaitai",
        "declarative",
        "data structure",
        "struct",
        "binary",
        "symmetric",
        "parser",
        "builder",
        "parsing",
        "building",
        "pack",
        "unpack",
        "packer",
        "unpacker",
    ],
    classifiers = [
        "Development Status :: 5 - Production/Stable",
        "License :: OSI Approved :: MIT License",
        "Intended Audience :: Developers",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Software Development :: Build Tools",
        "Topic :: Software Development :: Code Generators",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Programming Language :: Python :: 3.14",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
    ],
)
